"""add marketplace tables

Revision ID: 34360a491f30
Revises: fe56fa70289e
Create Date: 2026-10-03 18:14:46.731566

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '34360a491f30'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditlog',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('entity_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditlog_action'), 'auditlog', ['action'], unique=False)
    op.create_index(op.f('ix_auditlog_actor_id'), 'auditlog', ['actor_id'], unique=False)
    op.create_table('discountrule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('new_customers_only', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discountrule_code'), 'discountrule', ['code'], unique=True)
    op.create_table('featureflag',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('membershipplan',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('tier', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('interval', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('trial_days', sa.Integer(), nullable=False),
    sa.Column('lead_fee_cents', sa.Integer(), nullable=True),
    sa.Column('paypal_plan_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('paypal_product_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_membershipplan_code'), 'membershipplan', ['code'], unique=True)
    op.create_index(op.f('ix_membershipplan_paypal_plan_id'), 'membershipplan', ['paypal_plan_id'], unique=True)
    op.create_table('platformsetting',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('projectmodifier',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projectmodifier_code'), 'projectmodifier', ['code'], unique=True)
    op.create_table('webhookevent',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('paypal_event_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('environment', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('raw_body', sa.Text(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhookevent_event_type'), 'webhookevent', ['event_type'], unique=False)
    op.create_index(op.f('ix_webhookevent_paypal_event_id'), 'webhookevent', ['paypal_event_id'], unique=True)
    op.create_table('profile',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_company', sa.Boolean(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_user_id'), 'profile', ['user_id'], unique=True)
    op.create_table('project',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('project_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('service_area', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('budget_min_cents', sa.Integer(), nullable=True),
    sa.Column('budget_max_cents', sa.Integer(), nullable=True),
    sa.Column('desired_timeline', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('specialties', sa.JSON(), nullable=True),
    sa.Column('is_remote', sa.Boolean(), nullable=False),
    sa.Column('is_onsite', sa.Boolean(), nullable=False),
    sa.Column('is_urgent', sa.Boolean(), nullable=False),
    sa.Column('is_after_hours', sa.Boolean(), nullable=False),
    sa.Column('modifier_codes', sa.JSON(), nullable=True),
    sa.Column('privacy_requested', sa.Boolean(), nullable=False),
    sa.Column('contact_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('contact_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('contact_phone', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('street_address', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('awarded_bid_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_owner_id'), 'project', ['owner_id'], unique=False)
    op.create_table('selleraccount',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('paypal_merchant_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('onboarding_complete', sa.Boolean(), nullable=False),
    sa.Column('payments_receivable', sa.Boolean(), nullable=False),
    sa.Column('delayed_disbursement_enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_selleraccount_paypal_merchant_id'), 'selleraccount', ['paypal_merchant_id'], unique=False)
    op.create_index(op.f('ix_selleraccount_user_id'), 'selleraccount', ['user_id'], unique=True)
    op.create_table('subscription',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('paypal_subscription_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('trial_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['membershipplan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_paypal_subscription_id'), 'subscription', ['paypal_subscription_id'], unique=True)
    op.create_index(op.f('ix_subscription_user_id'), 'subscription', ['user_id'], unique=False)
    op.create_table('bid',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('professional_id', sa.Uuid(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('timeline_days', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['professional_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'professional_id')
    )
    op.create_index(op.f('ix_bid_professional_id'), 'bid', ['professional_id'], unique=False)
    op.create_index(op.f('ix_bid_project_id'), 'bid', ['project_id'], unique=False)
    op.create_table('leadunlock',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('professional_id', sa.Uuid(), nullable=False),
    sa.Column('fee_cents', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('paypal_order_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('paypal_capture_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['professional_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paypal_order_id'),
    sa.UniqueConstraint('project_id', 'professional_id')
    )
    op.create_index(op.f('ix_leadunlock_professional_id'), 'leadunlock', ['professional_id'], unique=False)
    op.create_index(op.f('ix_leadunlock_project_id'), 'leadunlock', ['project_id'], unique=False)
    op.create_table('milestone',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('seller_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_milestone_project_id'), 'milestone', ['project_id'], unique=False)
    op.create_table('subscriptionpayment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=False),
    sa.Column('paypal_transaction_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptionpayment_paypal_transaction_id'), 'subscriptionpayment', ['paypal_transaction_id'], unique=True)
    op.create_index(op.f('ix_subscriptionpayment_subscription_id'), 'subscriptionpayment', ['subscription_id'], unique=False)
    op.create_table('payment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('milestone_id', sa.Uuid(), nullable=True),
    sa.Column('payer_id', sa.Uuid(), nullable=False),
    sa.Column('seller_id', sa.Uuid(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('fee_cents', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('disbursement_mode', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('paypal_order_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('paypal_authorization_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('paypal_capture_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('paypal_merchant_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('released_cents', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('release_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestone.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payer_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paypal_order_id')
    )
    op.create_index(op.f('ix_payment_milestone_id'), 'payment', ['milestone_id'], unique=False)
    op.create_index(op.f('ix_payment_paypal_capture_id'), 'payment', ['paypal_capture_id'], unique=False)
    op.create_index(op.f('ix_payment_project_id'), 'payment', ['project_id'], unique=False)
    op.create_index(op.f('ix_payment_release_deadline'), 'payment', ['release_deadline'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_release_deadline'), table_name='payment')
    op.drop_index(op.f('ix_payment_project_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_paypal_capture_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_milestone_id'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_subscriptionpayment_subscription_id'), table_name='subscriptionpayment')
    op.drop_index(op.f('ix_subscriptionpayment_paypal_transaction_id'), table_name='subscriptionpayment')
    op.drop_table('subscriptionpayment')
    op.drop_index(op.f('ix_milestone_project_id'), table_name='milestone')
    op.drop_table('milestone')
    op.drop_index(op.f('ix_leadunlock_project_id'), table_name='leadunlock')
    op.drop_index(op.f('ix_leadunlock_professional_id'), table_name='leadunlock')
    op.drop_table('leadunlock')
    op.drop_index(op.f('ix_bid_project_id'), table_name='bid')
    op.drop_index(op.f('ix_bid_professional_id'), table_name='bid')
    op.drop_table('bid')
    op.drop_index(op.f('ix_subscription_user_id'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_paypal_subscription_id'), table_name='subscription')
    op.drop_table('subscription')
    op.drop_index(op.f('ix_selleraccount_user_id'), table_name='selleraccount')
    op.drop_index(op.f('ix_selleraccount_paypal_merchant_id'), table_name='selleraccount')
    op.drop_table('selleraccount')
    op.drop_index(op.f('ix_project_owner_id'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_profile_user_id'), table_name='profile')
    op.drop_table('profile')
    op.drop_index(op.f('ix_webhookevent_paypal_event_id'), table_name='webhookevent')
    op.drop_index(op.f('ix_webhookevent_event_type'), table_name='webhookevent')
    op.drop_table('webhookevent')
    op.drop_index(op.f('ix_projectmodifier_code'), table_name='projectmodifier')
    op.drop_table('projectmodifier')
    op.drop_table('platformsetting')
    op.drop_index(op.f('ix_membershipplan_paypal_plan_id'), table_name='membershipplan')
    op.drop_index(op.f('ix_membershipplan_code'), table_name='membershipplan')
    op.drop_table('membershipplan')
    op.drop_table('featureflag')
    op.drop_index(op.f('ix_discountrule_code'), table_name='discountrule')
    op.drop_table('discountrule')
    op.drop_index(op.f('ix_auditlog_actor_id'), table_name='auditlog')
    op.drop_index(op.f('ix_auditlog_action'), table_name='auditlog')
    op.drop_table('auditlog')
    # ### end Alembic commands ###
